import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` bg-[url('/assets/images/png/pizza-bg.png')] bg-cover bg-no-repeat bg-center`}
      >
        {children}
      </body>
    </html>
  );
}
